/* eslint-disable */
import "bootstrap";
import "./style.css";

import "./assets/img/rigo-baby.jpg";
import "./assets/img/4geeks.ico";
// Spades
let aceOfSpades;
let twoOfSpades;
let threeOfSpades;
let fourOfSpades;
let fiveOfSpades;
let sixOfSpades;
let sevenOfSpades;
let eightOfSpades;
let nineOfSpades;
let jackOfSpades;
let knightOfSpades;
let queenOfSpades;
let kingOfSpades;
// Hearts
let aceOfSpades;
let twoOfSpades;
let threeOfSpades;
let fourOfSpades;
let fiveOfSpades;
let sixOfSpades;
let sevenOfSpades;
let eightOfSpades;
let nineOfSpades;
let jackOfSpades;
let knightOfSpades;
let queenOfSpades;
let kingOfSpades;
// Diamonds
let aceOfSpades;
let twoOfSpades;
let threeOfSpades;
let fourOfSpades;
let fiveOfSpades;
let sixOfSpades;
let sevenOfSpades;
let eightOfSpades;
let nineOfSpades;
let jackOfSpades;
let knightOfSpades;
let queenOfSpades;
let kingOfSpades;
// Clubs
let aceOfSpades;
let twoOfSpades;
let threeOfSpades;
let fourOfSpades;
let fiveOfSpades;
let sixOfSpades;
let sevenOfSpades;
let eightOfSpades;
let nineOfSpades;
let jackOfSpades;
let knightOfSpades;
let queenOfSpades;
let kingOfSpades;
