/* eslint-disable */
import "bootstrap";
import "./style.css";

import "./assets/img/rigo-baby.jpg";
import "./assets/img/4geeks.ico";
// Spades
let aceOfSpades;
let twoOfSpades;
let threeOfSpades;
let fourOfSpades;
let fiveOfSpades;
let sixOfSpades;
let sevenOfSpades;
let eightOfSpades;
let nineOfSpades;
let jackOfSpades;
let knightOfSpades;
let queenOfSpades;
let kingOfSpades;
// Hearts
let aceOfHearts;
let twoOfHearts;
let threeOfHearts;
let fourOfHearts;
let fiveOfHearts;
let sixOfHearts;
let sevenOfHearts;
let eightOfHearts;
let nineOfHearts;
let jackOfHearts;
let knightOfHearts;
let queenOfHearts;
let kingOfHearts;
// Diamonds
let aceOfDiamonds;
let twoOfDiamonds;
let threeOfDiamonds;
let fourOfDiamonds;
let fiveOfDiamonds;
let sixOfDiamonds;
let sevenOfDiamonds;
let eightOfDiamonds;
let nineOfDiamonds;
let jackOfDiamonds;
let knightOfDiamonds;
let queenOfDiamonds;
let kingOfDiamonds;
// Clubs
let aceOfClubs;
let twoOfClubs;
let threeOfClubs;
let fourOfClubs;
let fiveOfClubs;
let sixOfClubs;
let sevenOfClubs;
let eightOfClubs;
let nineOfClubs;
let jackOfClubs;
let knightOfClubs;
let queenOfClubs;
let kingOfClubs;
// End
